name: A workflow for my fibonacci action
on: push

jobs:
  build:
    name: Run the fibonacci action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./fibonacci
        with:
          N_INDEX: 9
