name: A workflow for Fibonacci Series
on: [push,pull_request]

jobs:
  build:
    name: Fibonacci action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./Fibonacci Series
        with:
          N_INDEX: 9